apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u57ibb6hp-python 
  janus-idp.io/tekton: u57ibb6hp-python
  backstage.io/kubernetes-id: u57ibb6hp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u57ibb6hp-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml