apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u57ibb6hp-python
  janus-idp.io/tekton: u57ibb6hp-python
  backstage.io/kubernetes-id: u57ibb6hp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u57ibb6hp-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
